### ISSUE TITLE
API Service is defined twice

### ISSUE THREAD

**Issue by agrueneberg** [Taitrnator/OpenDisclosure-App#1]
Once in `client/assets/js/api.js` and in `client/assets/js/app.js`.

**Comment by Taitrnator** [comment]
Only works in app.js for now, but I couldn't get it to route right seperately based on the way foundation apps structures things

**Comment by agrueneberg** [comment]
Can you look into this? Just including the script in `index.html` doesn't work?

**Comment by Taitrnator** [comment]
I tried including a few different ways, but only way I'm able to make it work as of now is to inline it on app.js. I'll need to read up on the docs for foundation apps, its a bit different than conventional angular structure

**Comment by agrueneberg** [comment]
I couldn't find any mention of custom services in the documentation :/

**Comment by agrueneberg** [comment]
I just looked at the rest of Foundation Apps and while I like the components and the declarative way to handle templates, I'm concerned about two things:
First, it adds another layer of complexity on AngularJS, a framework already known for its complexity. The fact that easy things like adding services (a feature we will definitely need) is hard is telling.
Second, it brings back a build system. When I started on Open Disclosure the first change was to remove the dependency on the build system to reduce the learning curve. Not having a build system also facilitates the use of GitHub Pages, because it allows us to see the changes immediately once we push to the GitHub repository.

I have a suggestion: How about we stick to the current structure, but replace Bootstrap with Foundation (just the stylesheets)? That way you could even use SASS to generate the CSS and then check both files in. Do you already know which JS components of Foundation you would like to use? We could find replacements for those, or find a way to embed those into regular Angular (this is something where I'm sure we will find help on Stackoverflow if we happen to get stuck). What do you think?

**Comment by Taitrnator** [comment]
Yeah its starting to look that way. Oh well = / its a good idea but still not as easy to implement as it should be. 

Yeah, lets just stick with the original front end, and build it up with Foundation instead of bootstrap. Rebuilding it should fix some things that annoy me with the current look. I can do that this evening.

**Comment by agrueneberg** [comment]
Let me know how it goes. Note that I simplified the original repo structure a bit. I got rid of the shared folder, for instance.
